### ISSUE TITLE
erreur 404 lors du téléchargement de l'archive

### ISSUE THREAD

**Issue by VV666** [micgeri/zte-openc-flash-modem#1]
Bonjour, 
tout est dans le titre, ZTE a supprimer l'adresse à laquelle on pouvait trouvé l'archive utilisé dans le script, du coup ça ne marche plus.
Est-ce que l'on peut trouver le fichier ailleurs ?
Le script pourra-t-il être modifié pour utilisé un fichier local ?
Merci

**Comment by danielrocher** [comment]
J'ai fait un PR qui fixe ce problème
@++

**Comment by micgeri** [comment]
Bonjour,

Merge validé.
@danielrocher merci
